[2024-07-11T14:12:10.682+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ny_tlc_drivers_app.extract_data manual__2024-07-11T14:12:08.766506+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
