[2024-07-11T21:20:03.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T21:20:03.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:19:52.935911+00:00 [queued]>
[2024-07-11T21:20:03.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:19:52.935911+00:00 [queued]>
[2024-07-11T21:20:03.746+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-11T21:20:03.769+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-11 21:19:52.935911+00:00
[2024-07-11T21:20:03.778+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1652) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-11T21:20:03.781+0000] {standard_task_runner.py:63} INFO - Started process 1654 to run task
[2024-07-11T21:20:03.781+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ny_tlc_drivers_app', 'transform_data', 'manual__2024-07-11T21:19:52.935911+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/ny_tlc_drivers.py', '--cfg-path', '/tmp/tmpd_5k6cxb']
[2024-07-11T21:20:03.783+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask transform_data
[2024-07-11T21:20:03.893+0000] {task_command.py:426} INFO - Running <TaskInstance: ny_tlc_drivers_app.transform_data manual__2024-07-11T21:19:52.935911+00:00 [running]> on host 0c05e79c8db4
[2024-07-11T21:20:04.360+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_tlc_drivers_app' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T21:19:52.935911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T21:19:52.935911+00:00'
[2024-07-11T21:20:04.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T21:20:04.374+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T21:20:04.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform_data() missing 1 required positional argument: 'df'
[2024-07-11T21:20:04.412+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ny_tlc_drivers_app, task_id=transform_data, run_id=manual__2024-07-11T21:19:52.935911+00:00, execution_date=20240711T211952, start_date=20240711T212003, end_date=20240711T212004
[2024-07-11T21:20:04.476+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 63 for task transform_data (transform_data() missing 1 required positional argument: 'df'; 1654)
[2024-07-11T21:20:04.515+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T21:20:04.572+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T21:20:04.578+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
