[2024-07-11T00:08:56.329+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ny_tlc_drivers_app.extract manual__2024-07-11T00:08:55.087489+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
