[2024-07-11T00:02:22.372+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ny_tlc_drivers_app.extract scheduled__2024-07-10T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
